version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: nft
      POSTGRES_PASSWORD: nft
      POSTGRES_DB: nft
    ports:
      - '5434:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: closeSea
      RABBITMQ_DEFAULT_PASS: closeSeaP@ssword
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  node1:
      image: redis
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      ports:
      - '6379'
      networks:
      - redis_network

networks:
  redis_network:

#docker-compose up --scale node1=6
#docker-compose down -v

#  docker exec -it nft-node1-1 redis-cli —cluster create 172.30.0.5:6379 172.30.0.8:6379 172.30.0.10:6379 172.30.0.6:6379 172.30.0.9:6379 172.30.0.3:6379 172.30.0.4:6379 172.30.0.2:6379 172.30.0.7:6379 —cluster-replicas 1
