version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: nft
      POSTGRES_PASSWORD: nft
      POSTGRES_DB: nft
    ports:
      - '5434:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

