
spring:
  application:
    name: nft
  datasource:
    url: jdbc:postgresql://localhost:5434/nft
    username: nft
    password: nft
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/nft
    username: nft
    password: nft
  rabbitmq:
    host: localhost
    port: 5672
    username: closeSea
    password: closeSeaP@ssword


  data:
    redis:
      cluster:
        nodes:
          - 192.168.50.185:50667
          - 192.168.50.185:50668
          - 192.168.50.185:50669
          - 192.168.50.185:50670
          - 192.168.50.185:50671
          - 192.168.50.185:50672
        max-redirects: 3
      password: "foobared"
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0


logging:
  level:
    org.springframework.r2dbc: debug

#    io.r2dbc.postgresql: DEBUG
#    root: info
server:
  port: 8082

apikey:
  infura: "98b672d2ce9a4089a3a5cb5081dde2fa"
  moralis: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6ImJiNmIxMWJmLWNmNzItNDg0OC04OGEyLTBjYTIwODRjN2VhMyIsIm9yZ0lkIjoiMzgzODQwIiwidXNlcklkIjoiMzk0NDAyIiwidHlwZUlkIjoiMGZlYWQ5NDctZjQwZS00MDkwLWFlNGUtOTA1ZTdmMjUxZTAzIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MTA5NTIwMjYsImV4cCI6NDg2NjcxMjAyNn0.VQE60IPGiWxdp7jKLF0jzXnxrLjEpU56H4bnfhMt0Sw"