
spring:
  application:
    name: nft
  datasource:
    url: jdbc:postgresql://localhost:5434/nft
    username: nft
    password: nft
  flyway:
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/nft
    username: nft
    password: nft
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: localhost
    port: 5672
    username: closeSea
    password: closeSeaP@ssword
    queues:
      nft: "nftQueue"
    template:
      exchange: "exchange"
      routing-key: "routingKey"

logging:
  level:
    org.springframework.r2dbc: debug
#    io.r2dbc.postgresql: DEBUG
#    root: info
server:
  port: 8082
